import 'codemirror/mode/javascript/javascript.js';
// import 'codemirror/mode/shell/shell.js';
import 'codemirror/mode/ebnf/ebnf';
import 'codemirror/mode/handlebars/handlebars.js';
import 'codemirror/mode/htmlmixed/htmlmixed.js';
import 'codemirror/mode/xml/xml.js';
import 'codemirror/mode/css/css.js';
import 'codemirror/addon/edit/closebrackets.js';
import 'codemirror/addon/edit/closetag.js';
import 'codemirror/lib/codemirror.css';
import 'codemirror/keymap/vim.js';
import 'codemirror/theme/monokai.css';
import 'codemirror/theme/icecoder.css';
import 'codemirror/theme/shadowfox.css';
import 'codemirror/theme/cobalt.css';
import 'codemirror/addon/mode/multiplex';
import './theme.css';
import "./sema.css";